### ISSUE TITLE
No output on v1.2 with findbugs

### ISSUE THREAD

**Issue by sjudd** [tomasbjerre/violations-gradle-plugin#1]
I've attempted to add this to Glide here so that it's possible to see violations in travis-ci directly. There's a pending commit here: https://github.com/sjudd/glide/commit/5e21322a065f980c83df2a8d92a3c0069bbc643e.

I've added a findbugs failure which I see in the gradle output (`./gradlew :library:check`) but I don't see any output or failure from this plugin.

**Comment by tomasbjerre** [comment]
You need to specify the pattern to let the plugin identify the findbugs report-file. Also to make that task run after check has been completed.

Here is my script:
https://github.com/tomasbjerre/gradle-scripts/blob/master/src/main/resources/java.gradle

I use it in [git-changelog-lib](https://github.com/tomasbjerre/git-changelog-lib), if you do `./gradlew build -i` it will output some comments.

**Comment by sjudd** [comment]
Wups, added the violations task to that commit: https://github.com/sjudd/glide/commit/8bcafacca1692aff053402aca01d11fe0ce52bac.

`./gradlew :library:check` still produces no output, but adding -i does, thanks! It might be worth adding that to the readme if that's expected. I also see that you've mentioned that the plugin can "Optionally fail the build depending on violations found." in the readme, but I don't see the option to do that (though I'll probably find it by looking).

**Comment by tomasbjerre** [comment]
Ok. Yes it will fail if the maxViolations property is lower then number of found violations.

**Comment by sjudd** [comment]
Setting maxViolations to 0 does fail the build, but it doesn't produce the report without -i, would you mind changing it so that it logs the report without a failure only with -i but always logs the report if maxViolations is exceeded?

**Comment by tomasbjerre** [comment]
Im not sure how to do that. Perhaps the whole log can be the message string
of the exception that fails the build. But yes, Ill have a look.

Den 25 dec. 2017 22:19 skrev "Sam" <notifications@github.com>:

**Comment by sjudd** [comment]
Yeah I was thinking I'd try that. I'm happy to try to figure it out and send you a pull request, it may take me a few days because I'll have to get approval for the patch before I send it, but perhaps there's no rush. 

Thanks for doing this, neat library!

**Comment by tomasbjerre** [comment]
Ok yes, sure!
