### ISSUE TITLE
checkstyle not being parsed

### ISSUE THREAD

**Issue by kfot** [tomasbjerre/violations-gradle-plugin#10]
First of all - thanks for the great plugin.

Issue: checkstyle report results not included in violations summary because the parser not respects the non-default `configFile` dir. 

I'm using default checkstyle gradle plugin with a multi-module Java 11 project, Gradle 5.1.1

`$ ./gradlew violations -d` shows that these dirs are being checked
```
15:44:09.560 [DEBUG] [ViolationsApi] /work/.gradle/daemon/5.1.1/./checkstyle/checkstyle.xml
15:44:09.560 [DEBUG] [ViolationsApi] /work/.gradle/daemon/5.1.1/./config/checkstyle/checkstyle.xml
15:44:09.561 [DEBUG] [ViolationsApi] Found 0 violations:
```
despite such checkstyle settings from `build.gradle`

```
    checkstyle {
        toolVersion = "8.16"
        ignoreFailures = true
        showViolations = true
        configFile = new File(rootDir, "checkstyle/checkstyle.xml")
//        reportsDir = new File(project.buildDir, "reports/checkstyle") <- explicit setting did not change anything
    }
```
In fact, checkstyle reports are within the dafault path ( next to `pmd` and `spotbugs` reports which work fine)
```
my-multi-module-project/hello-world/build/reports/checkstyle/main.xml
```
and my regex is as in your example (as I mentioned, it works for pmd and spotbugs but not for checkstyle)
```
        violations = [
                ["FINDBUGS",   ".",  ".*/spotbugs/.*\\.xml\$",  "Spotbugs"],
                ["PMD",        ".",  ".*/pmd/.*\\.xml\$",       "PMD"],
                ["CHECKSTYLE", ".",  ".*/checkstyle/*\\.xml\$", "Checkstyle"],
        ]
```

**Comment by tomasbjerre** [comment]
The plugin searches a folder that is pointed out with `.` in your example.

Here: https://github.com/tomasbjerre/violations-gradle-plugin/blob/master/src/main/java/se/bjurr/violations/gradle/plugin/ViolationsTask.java#L212

And in the lib: https://github.com/tomasbjerre/violations-lib/blob/50bcfaaf1afdbdd8c456a283e2f7fb4530720f7b/src/main/java/se/bjurr/violations/lib/ViolationsApi.java#L39

Perhaps try:
```
        violations = [
                ["FINDBUGS",   project.buildDir,  ".*/spotbugs/.*\\.xml\$",  "Spotbugs"],
                ["PMD",        project.buildDir,  ".*/pmd/.*\\.xml\$",       "PMD"],
                ["CHECKSTYLE", project.buildDir,  ".*/checkstyle/*\\.xml\$", "Checkstyle"],
        ]
```
