### ISSUE TITLE
Version 2.1.2 fails to parse detekt results file. 

### ISSUE THREAD

**Issue by bay73** [tomasbjerre/violations-gradle-plugin#22]
While parsing detekt output xml file an exception occurs:

`java.lang.RuntimeException: "se.bjurr.violations.violationsgitlib.severity" not found in: <?xml version="1.0" encoding="UTF-8"?><error line="62" column="21" severity="warning" message="Forbidden TODO todo marker in comment, please do the changes." source="detekt.ForbiddenComment"/>`

Decompiled code of CheckStyleParser really has `se.bjurr.violations.violationsgitlib.severity` instead of just 'severity':
```
column = ViolationParserUtils.findIntegerAttribute(xmlr, "column");
severity = ViolationParserUtils.getAttribute(xmlr, "se.bjurr.violations.violationsgitlib.severity");
message = ViolationParserUtils.getAttribute(xmlr, "message");
```

Not sure where this came from.

**Comment by tomasbjerre** [comment]
Does 2.2.0 work?

I also noticed this bug. Seems like a bug in the Shadow tool.

**Comment by bay73** [comment]
2.2.0 is not available yet at https://plugins.gradle.org/

**Comment by tomasbjerre** [comment]
I published `2.2.2` now. Hope that works.

https://github.com/gradle/plugin-portal-requests/issues/242

**Comment by tomasbjerre** [comment]
Open issue again if not working

**Comment by bay73** [comment]
Thank you. Version 2.2.2 works
