### ISSUE TITLE
Single quotes in xml are printed as &apos;

### ISSUE THREAD

**Issue by sjudd** [tomasbjerre/violations-gradle-plugin#4]
Here's an example from the checkstyle plugin:
```
╔════════════╤═════════════════════════════════════════════════════════════════╤══════════╤══════╤═════════════════════════════════════════════════════════════════════╗
  ║ Reporter   │ Rule                                                            │ Severity │ Line │ Message                                                             ║
  ╠════════════╪═════════════════════════════════════════════════════════════════╪══════════╪══════╪═════════════════════════════════════════════════════════════════════╣
  ║ Checkstyle │ com.puppycrawl.tools.checkstyle.checks.imports.ImportOrderCheck │ ERROR    │ 6    │ Wrong order for &apos;android.content.ContentResolver&apos; import. ║
  ╚════════════╧═════════════════════════════════════════════════════════════════╧══════════╧══════╧═════════════════════════════════════════════════════════════════════╝
```

It's probably possible to render them as expected, if nothing else by just replacing the few special characters xml seems to allow: http://xml.silmaril.ie/specials.html. 

I'll also try and look in to it, just filing this as a reminder.

**Comment by tomasbjerre** [comment]
I'd really like to keep [the pom of the lib](http://search.maven.org/remotecontent?filepath=se/bjurr/violations/violations-lib/1.48/violations-lib-1.48.pom) free from dependencies.

But there is also the argument of not re-implementing a bunch of utilities...

So perhaps it is best to add Guava to the lib, and [relocate it](https://github.com/tomasbjerre/violations-lib/blob/master/build.gradle) in the jar.

**Comment by sjudd** [comment]
I think I missed something, do you think Guava has a utility that would interpret these symbols?

**Comment by tomasbjerre** [comment]
Yes. Perhaps this one: https://google.github.io/guava/releases/19.0/api/docs/com/google/common/html/HtmlEscapers.html

**Comment by sjudd** [comment]
Closing this in favor of https://github.com/tomasbjerre/violations-lib/issues/28.
